name: k0nnect
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.9.1
  #for getting cached images from gmail profile
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  emoji_picker_flutter: ^1.6.2
  firebase_messaging: ^14.6.9
  http: 0.13.6
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/