// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9u2-WCLbH0kQNc0mAtETD3JwCimZ4JA',
    appId: '1:819716880146:android:6ccf85ee2dde3984fc25cb',
    messagingSenderId: '819716880146',
    projectId: 'k0nnect-1274c',
    storageBucket: 'k0nnect-1274c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdLliIwQzrWjoh_namFLpAkzAaXI7cF-8',
    appId: '1:819716880146:ios:f974af3bd2204c9dfc25cb',
    messagingSenderId: '819716880146',
    projectId: 'k0nnect-1274c',
    storageBucket: 'k0nnect-1274c.appspot.com',
    androidClientId: '819716880146-qfgr5oq0n9hmmokn8tvfue5teq4mdnk0.apps.googleusercontent.com',
    iosClientId: '819716880146-hps8s6sib6ls4f2l7ovqf8eud1j8vptl.apps.googleusercontent.com',
    iosBundleId: 'com.example.k0nnect',
  );
}
